### PR TITLE
fix minor commandline mistake

### PR DESCRIPTION
**Pull request by jeff-hykin**

### CODE REVIEW

**Comment by robertgzr** [comment]
That line refers to the https://github.com/robertgzr/homebrew-tap/blob/master/iosevka.rb which has a bunch of options that one can look at using the `info` command.

`iosevka-font` was removed from this tap: https://github.com/robertgzr/homebrew-tap/commit/bd152787b4dfbd5703530bd6a6a43b5719f8db0e

**Comment by jeff-hykin** [comment]
I apologize for that, thanks for providing the links.
It appears now that neither of the commands work for me.

Screen Shot 2020-01-20 at 6 40 42 PM

### If this doesn't reproduce for you, then don't worry about responding
Its not a real problem for me, I just figured I'd help improve the experience for others.
FYI, I have the fonts tap installed which I'm sure is relevant for the following screenshot

Screen Shot 2020-01-20 at 6 43 31 PM

**Comment by robertgzr** [comment]
It looks like you have `font-iosevka` available from two separate casks...

I'm not sure what the difference between `caskroom/fonts` and `homebrew/cask-fonts` is, but that error would be expected in this case.

Note that the `iosevka` formula is not a cask, it will build the font from it's source code to allow full customizability. It has to be use like this:

```
$ brew install iosevka
```

**Comment by jeff-hykin** [comment]
Screen Shot 2020-01-26 at 11 15 15 PM

**Pull request closed without merging**
